### ISSUE TITLE
about the anomaly score

### ISSUE THREAD

**Issue by cuixianheng** [yuguangnudt/VEC_VAD#1]
hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
I am very appreciate if you give me some advice

**Comment by yuguangnudt** [comment]
> hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> I am very appreciate if you give me some advice

**Comment by yuguangnudt** [comment]
> hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> I am very appreciate if you give me some advice

**Comment by yuguangnudt** [comment]
> hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> I am very appreciate if you give me some advice

Of course all STCs are used. Due to the limitation of space in this paper, we only specify the calculation method of anomaly score of a STC instead of a whole frame. In the experiment, the largest STC anomaly score in a frame is used as the anomaly score for this frame. You can refer to lines 366-373 and 402-414 in test.py.

**Comment by algorithmlixuan** [comment]
> > hi, I have a question about your paper. A frame maybe have some STC, but the anomaly score in your method only one STC. When you judge whether an frame is an abnormal，are all STCs in this frame used?
> > I am very appreciate if you give me some advice
> 
> Of course all STCs are used. Due to the limitation of space in this paper, we only specify the calculation method of anomaly score of a STC instead of a whole frame. In the experiment, the largest STC anomaly score in a frame is used as the anomaly score for this frame. You can refer to lines 366-373 and 402-414 in test.py.

Hi, thanks for your inspiring work. I have a question:
why does one frame have some STCs? According to this figure in your paper, one STC should have multiple frames instead of multiple STCs per frame
I am very appreciate if you give me some advice

![image](https://user-images.githubusercontent.com/30352320/96693146-73f14000-13b9-11eb-84c7-e2176d32ffa0.png)
